### ISSUE TITLE
Move src out of kanonproxy module

### ISSUE THREAD

**Issue by compscidr** [compscidr/kanonproxy#9]
Since there are no other modules, we can move the src right to the root folder, see https://github.com/compscidr/test-servers for an example of how this might be configured.

**Comment by JP-sDEV** [comment]
Hi @compscidr, could I take on this issue?

**Comment by compscidr** [comment]
That would be great thanks. Also if you're interested - one of the dependencies of this project has a similar issue and is structured almost the same as this: https://github.com/compscidr/knet/issues/33

**Comment by compscidr** [comment]
Completed by https://github.com/compscidr/kanonproxy/pull/12
